spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: {secret.cognito_client_id}
            client-secret: {secret.cognito_client_secret}
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/cognito"
            scope:
              - openid
              - email
              - phone
        provider:
          cognito:
            issuerUri: {secret.cognito_issued_url}
            user-name-attribute: username