spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: REMOVED
            client-secret: REMOVED
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/cognito"
            scope:
              - openid
              - email
              - phone
        provider:
          cognito:
            issuerUri: REMOVED
            user-name-attribute: username