spring.application.name=cognitoService
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web: DEBUG
cognito.domain=https://us-east-1g7d8asdiu.auth.us-east-1.amazoncognito.com
cognito.logout.url=https://us-east-1g7d8asdiu.auth.us-east-1.amazoncognito.com/logout
cognito.client.id=46fj8ebvp0o7h5791hp19voceb
cognito.logout.redirect.uri=http://localhost:3000
#cognito.user.pool.id=46fj8ebvp0o7h5791hp19voceb
frontend.url=http://localhost:3000
logout.url=http://localhost:3000